source/probability_theory_4_finite.Rmd

Please review Problem 8-5; I got different results from the book after I rewrote the problem, so I could have introduced a change there.
I also got a different answer for the last problem, but I think my code is correct in that case?

Rework code for probability theory 4 finite

---

.travis.yml
source/Makefile
source/probability_theory_4_finite.Rmd

np.repeat is awesome

---

source/_common.R

Table is a common command in base R

Rename table command

---

scripts/rebuild_chapter.sh
source/_common.R
source/resampling_method.Rmd

Yes, I know, I'm sorry.
I here avoided explaining what an 'integer' was, and the one-less-than high
thing, deferring this for the later chapters.

MRG: rewrite resampling methods chapter

---

source/_common.R
source/references.Rmd
source/resampling_method.Rmd

Various small tweaks to PDF formatting.

MRG: Fixing some formatting for PDF document

---

source/_quarto.yml.template

From: https://quarto.org/docs/authoring/cross-references.html#options
Closes gh-39.

Rename inline references to sections, figs, tables

---

.github/workflows/build.yaml
.gitignore
.gitmodules
build-requirements.txt
source/Makefile
source/_quarto.yml.template
source/about_technology.Rmd
source/filters/filter_divspans.py
source/filters/filter_nb_only.py
source/filters/filter_pre.py
source/filters/write_notebooks.py

Move noteout scripts to standalone files.
Fix Inkscape deprecation warning

Fixes for latest quarto

---

.gitignore
source/about_technology.Rmd
source/about_technology_r.Rmd
source/index.Rmd

Some notebook and .gitignore edits from Stefan's first run through
getting the book working for newer Quarto.

MRG: some edits from Stefan's refactoring

---

scripts/install_r_requirements.R
source/_common.R

Use Jupyter-compatibility mode for Reticulate.

Try our Reticulate edits for plot generation

---

source/bayes_simulation.Rmd
source/dramatizing_resampling.Rmd
source/software-intro.Rmd

Sum was a bit easier to explain, and we started using it at the start of
the book.
Closes gh-38

Replace count_nonzero with sum

---

README.md

Move a misplaced paragraph in README.

Move paragraph in README

---

source/more_sampling_tools.Rmd
source/text_variables.yml

Work through more explanation of Boolean arrays.
Will continue through Monty Hall problem.  After which, I think we have decent
tutorial background for everything we need.  Of course, might consider e.g.
functions later.

MRG: Develop Boolean arrays

---

source/bayes_simulation.Rmd
source/significance.Rmd

Very small edits, remove warning.

MRG: significance chapter

---

source/confidence_2.Rmd
source/simon_refs.bib

Just some edits going through.  Found reference.

MRG: Confidence rework

---

source/reliability_average.Rmd

MRG: rework reliability of sample average

---

README.md
source/inference_ideas.Rmd
source/simon_refs.bib

I think this one's a straight improvement - I suggest merging soon.

MRG: Fixing tables and refs for inference_ideas

---

source/monte_carlo.Rmd
source/probability_theory_1a.Rmd

Rewrite and rearrange for clarity

Rework Monte-Carlo chapter

---

source/_common.R
source/_common.py

We're using default_rng throughout, so monkeypatch to always seed that
(but just for the page builds).

MRG: Also seed Python default_rng

---

source/confidence_2.Rmd

Add Theban jars code example

---

notes/general.md
source/bayes_simulation.Rmd
source/intro.Rmd
source/preface_third.Rmd
source/probability_theory_2_compound.Rmd
source/what_is_probability.Rmd

Reverts resampling-stats/resampling-with#135 - @ben-herbst - this is what you meant I guess?    Can you reopen your pull-request?

Revert "Ben/bayesian analysis"

---

source/generate-ninja.py

Otherwise, the div filtering may not be executed as necessary.

Clean up before building another language

---

source/bayes_simulation.Rmd

Various edits for standardizing variable names, use of rng, removing use of
lists (which we haven't covered).
Comments @stefanv?

Reworking Bayes simulation
